name: dermao-influencer-connect
services:
- name: api
  source_dir: /
  github:
    repo: permain2/Influencermarketingbot
    branch: main
  build_command: |
    npm ci
    cd frontend && npm ci && npm run build
  run_command: node src/app.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: FIREBASE_PROJECT_ID
    value: influencer-marketing-bot
    type: SECRET
  - key: FIREBASE_PRIVATE_KEY_ID
    type: SECRET
  - key: FIREBASE_PRIVATE_KEY
    type: SECRET
  - key: FIREBASE_CLIENT_EMAIL
    type: SECRET
  - key: FIREBASE_CLIENT_ID
    type: SECRET
  - key: BREVO_API_KEY
    type: SECRET
  - key: FROM_EMAIL
  - key: FROM_NAME
    value: Dermao Partnership Team
  - key: EMAIL_PROVIDER
    value: brevo
  - key: APIFY_API_TOKEN
    type: SECRET
  - key: SHOPIFY_SHOP_NAME
    type: SECRET
  - key: SHOPIFY_ACCESS_TOKEN
    type: SECRET
  - key: SHOPIFY_API_KEY
    type: SECRET
  - key: SHOPIFY_API_SECRET
    type: SECRET
  - key: DEFAULT_PRODUCT_VALUE
    value: "299"
  - key: CAMPAIGN_HASHTAG
    value: "#DermaoPartner"
  - key: BRAND_INSTAGRAM
    value: "@dermao.official"
  - key: GEMINI_API_KEY
    type: SECRET
  - key: AI_PROVIDER
    value: gemini
  - key: SUPABASE_URL
    type: SECRET
  - key: SUPABASE_ANON_KEY
    type: SECRET
  - key: VITE_API_BASE_URL
    value: "https://dermao-influencer-connect-xxxxx.ondigitalocean.app"
  http_port: 8080
  routes:
  - path: / 